#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALX_MPES_BOL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ALX_MPES")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_Account(TBL_Account instance);
    partial void UpdateTBL_Account(TBL_Account instance);
    partial void DeleteTBL_Account(TBL_Account instance);
    partial void InsertTBL_Criteria(TBL_Criteria instance);
    partial void UpdateTBL_Criteria(TBL_Criteria instance);
    partial void DeleteTBL_Criteria(TBL_Criteria instance);
    partial void InsertTBL_EvaluationCriteria_catagory(TBL_EvaluationCriteria_catagory instance);
    partial void UpdateTBL_EvaluationCriteria_catagory(TBL_EvaluationCriteria_catagory instance);
    partial void DeleteTBL_EvaluationCriteria_catagory(TBL_EvaluationCriteria_catagory instance);
    partial void InsertTBL_Mentor(TBL_Mentor instance);
    partial void UpdateTBL_Mentor(TBL_Mentor instance);
    partial void DeleteTBL_Mentor(TBL_Mentor instance);
    partial void InsertTBL_Menu(TBL_Menu instance);
    partial void UpdateTBL_Menu(TBL_Menu instance);
    partial void DeleteTBL_Menu(TBL_Menu instance);
    partial void InsertTBL_Student(TBL_Student instance);
    partial void UpdateTBL_Student(TBL_Student instance);
    partial void DeleteTBL_Student(TBL_Student instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_Account> TBL_Accounts
		{
			get
			{
				return this.GetTable<TBL_Account>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Criteria> TBL_Criterias
		{
			get
			{
				return this.GetTable<TBL_Criteria>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Departement> TBL_Departements
		{
			get
			{
				return this.GetTable<TBL_Departement>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Evaluation_Data> TBL_Evaluation_Datas
		{
			get
			{
				return this.GetTable<TBL_Evaluation_Data>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Evaluation_Result> TBL_Evaluation_Results
		{
			get
			{
				return this.GetTable<TBL_Evaluation_Result>();
			}
		}
		
		public System.Data.Linq.Table<TBL_EvaluationCriteria_catagory> TBL_EvaluationCriteria_catagories
		{
			get
			{
				return this.GetTable<TBL_EvaluationCriteria_catagory>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Mentor> TBL_Mentors
		{
			get
			{
				return this.GetTable<TBL_Mentor>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Mentor_evaluation_Result> TBL_Mentor_evaluation_Results
		{
			get
			{
				return this.GetTable<TBL_Mentor_evaluation_Result>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Menu> TBL_Menus
		{
			get
			{
				return this.GetTable<TBL_Menu>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Student> TBL_Students
		{
			get
			{
				return this.GetTable<TBL_Student>();
			}
		}
		
		public System.Data.Linq.Table<TBL_UsermenuRole> TBL_UsermenuRoles
		{
			get
			{
				return this.GetTable<TBL_UsermenuRole>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addevaluationCriteria")]
		public int addevaluationCriteria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CriteriaID", DbType="NVarChar(50)")] string criteriaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CriteriaName", DbType="NVarChar(50)")] string criteriaName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Createdby", DbType="NVarChar(50)")] string createdby)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), criteriaID, criteriaName, createdby);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addevaluationdata")]
		public int addevaluationdata([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string mentorID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string evaluatorid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string criteriaid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> criteriaresult)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mentorID, evaluatorid, criteriaid, criteriaresult);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addevaulationresult")]
		public int addevaulationresult([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string mentorid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string evaluatorid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mentorid, evaluatorid, result);
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.averageresult")]
		public int averageresult([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string mentorname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Average_result", DbType="Real")] System.Nullable<float> average_result)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mentorname, average_result);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.createaccount")]
		public int createaccount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string dept, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> astatus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string createdby, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string role)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, fname, lname, email, dept, username, password, astatus, createdby, role);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.createaccount")]
		public int createaccount1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string dept, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> astatus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string createdby, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string role)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, fname, lname, email, dept, username, password, astatus, createdby, role);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddMenu")]
		public int AddMenu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string menuid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string parentmenu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string menuname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string link)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), menuid, parentmenu, menuname, link);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AssignRole")]
		public int AssignRole([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string uname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string menuid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string assignedby, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uname, menuid, status, assignedby, date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registermentor")]
		public int registermentor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string mid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string mfname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string mmname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string mlname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string dept, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string special)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mid, mfname, mmname, mlname, email, dept, special);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddDept")]
		public int AddDept([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string deptcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string deptname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deptcode, deptname);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatepassword")]
		public int updatepassword([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), password, username);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Account")]
	public partial class TBL_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _User_ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Email;
		
		private string _Department;
		
		private string _Username;
		
		private string _password;
		
		private int _Account_status;
		
		private System.DateTime _Created_Date;
		
		private string _Created_by;
		
		private string _Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IDChanging(string value);
    partial void OnUser_IDChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnAccount_statusChanging(int value);
    partial void OnAccount_statusChanged();
    partial void OnCreated_DateChanging(System.DateTime value);
    partial void OnCreated_DateChanged();
    partial void OnCreated_byChanging(string value);
    partial void OnCreated_byChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    #endregion
		
		public TBL_Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account_status", DbType="Int NOT NULL")]
		public int Account_status
		{
			get
			{
				return this._Account_status;
			}
			set
			{
				if ((this._Account_status != value))
				{
					this.OnAccount_statusChanging(value);
					this.SendPropertyChanging();
					this._Account_status = value;
					this.SendPropertyChanged("Account_status");
					this.OnAccount_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="Date NOT NULL")]
		public System.DateTime Created_Date
		{
			get
			{
				return this._Created_Date;
			}
			set
			{
				if ((this._Created_Date != value))
				{
					this.OnCreated_DateChanging(value);
					this.SendPropertyChanging();
					this._Created_Date = value;
					this.SendPropertyChanged("Created_Date");
					this.OnCreated_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_by", DbType="NVarChar(50)")]
		public string Created_by
		{
			get
			{
				return this._Created_by;
			}
			set
			{
				if ((this._Created_by != value))
				{
					this.OnCreated_byChanging(value);
					this.SendPropertyChanging();
					this._Created_by = value;
					this.SendPropertyChanged("Created_by");
					this.OnCreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(50)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Criteria")]
	public partial class TBL_Criteria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _CriteriaID;
		
		private string _CriteriaName;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.TimeSpan> _Createdtime;
		
		private string _Createdby;
		
		private string _Modifiedby;
		
		private System.Nullable<System.DateTime> _Modifieddate;
		
		private System.Nullable<System.TimeSpan> _Modifiedtime;
		
		private System.Nullable<int> _modstatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCriteriaIDChanging(string value);
    partial void OnCriteriaIDChanged();
    partial void OnCriteriaNameChanging(string value);
    partial void OnCriteriaNameChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnCreatedtimeChanged();
    partial void OnCreatedbyChanging(string value);
    partial void OnCreatedbyChanged();
    partial void OnModifiedbyChanging(string value);
    partial void OnModifiedbyChanged();
    partial void OnModifieddateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifieddateChanged();
    partial void OnModifiedtimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnModifiedtimeChanged();
    partial void OnmodstatusChanging(System.Nullable<int> value);
    partial void OnmodstatusChanged();
    #endregion
		
		public TBL_Criteria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriteriaID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CriteriaID
		{
			get
			{
				return this._CriteriaID;
			}
			set
			{
				if ((this._CriteriaID != value))
				{
					this.OnCriteriaIDChanging(value);
					this.SendPropertyChanging();
					this._CriteriaID = value;
					this.SendPropertyChanged("CriteriaID");
					this.OnCriteriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriteriaName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CriteriaName
		{
			get
			{
				return this._CriteriaName;
			}
			set
			{
				if ((this._CriteriaName != value))
				{
					this.OnCriteriaNameChanging(value);
					this.SendPropertyChanging();
					this._CriteriaName = value;
					this.SendPropertyChanged("CriteriaName");
					this.OnCriteriaNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> Createdtime
		{
			get
			{
				return this._Createdtime;
			}
			set
			{
				if ((this._Createdtime != value))
				{
					this.OnCreatedtimeChanging(value);
					this.SendPropertyChanging();
					this._Createdtime = value;
					this.SendPropertyChanged("Createdtime");
					this.OnCreatedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Createdby", DbType="NVarChar(50)")]
		public string Createdby
		{
			get
			{
				return this._Createdby;
			}
			set
			{
				if ((this._Createdby != value))
				{
					this.OnCreatedbyChanging(value);
					this.SendPropertyChanging();
					this._Createdby = value;
					this.SendPropertyChanged("Createdby");
					this.OnCreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifiedby", DbType="NVarChar(50)")]
		public string Modifiedby
		{
			get
			{
				return this._Modifiedby;
			}
			set
			{
				if ((this._Modifiedby != value))
				{
					this.OnModifiedbyChanging(value);
					this.SendPropertyChanging();
					this._Modifiedby = value;
					this.SendPropertyChanged("Modifiedby");
					this.OnModifiedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifieddate", DbType="Date")]
		public System.Nullable<System.DateTime> Modifieddate
		{
			get
			{
				return this._Modifieddate;
			}
			set
			{
				if ((this._Modifieddate != value))
				{
					this.OnModifieddateChanging(value);
					this.SendPropertyChanging();
					this._Modifieddate = value;
					this.SendPropertyChanged("Modifieddate");
					this.OnModifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modifiedtime", DbType="Time")]
		public System.Nullable<System.TimeSpan> Modifiedtime
		{
			get
			{
				return this._Modifiedtime;
			}
			set
			{
				if ((this._Modifiedtime != value))
				{
					this.OnModifiedtimeChanging(value);
					this.SendPropertyChanging();
					this._Modifiedtime = value;
					this.SendPropertyChanged("Modifiedtime");
					this.OnModifiedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modstatus", DbType="Int")]
		public System.Nullable<int> modstatus
		{
			get
			{
				return this._modstatus;
			}
			set
			{
				if ((this._modstatus != value))
				{
					this.OnmodstatusChanging(value);
					this.SendPropertyChanging();
					this._modstatus = value;
					this.SendPropertyChanged("modstatus");
					this.OnmodstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Departement")]
	public partial class TBL_Departement
	{
		
		private string _Dept_code;
		
		private string _Dept_name;
		
		public TBL_Departement()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_code", DbType="NVarChar(50)")]
		public string Dept_code
		{
			get
			{
				return this._Dept_code;
			}
			set
			{
				if ((this._Dept_code != value))
				{
					this._Dept_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_name", DbType="NVarChar(50)")]
		public string Dept_name
		{
			get
			{
				return this._Dept_name;
			}
			set
			{
				if ((this._Dept_name != value))
				{
					this._Dept_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Evaluation_Data")]
	public partial class TBL_Evaluation_Data
	{
		
		private int _id;
		
		private string _mentor_id;
		
		private string _evaluator_id;
		
		private System.Nullable<System.DateTime> _evaluation_date;
		
		private string _CriteriaID;
		
		private System.Nullable<int> _Criteria_result;
		
		private System.Nullable<System.DateTime> _Acc_year;
		
		public TBL_Evaluation_Data()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mentor_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string mentor_id
		{
			get
			{
				return this._mentor_id;
			}
			set
			{
				if ((this._mentor_id != value))
				{
					this._mentor_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaluator_id", DbType="NVarChar(50)")]
		public string evaluator_id
		{
			get
			{
				return this._evaluator_id;
			}
			set
			{
				if ((this._evaluator_id != value))
				{
					this._evaluator_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaluation_date", DbType="Date")]
		public System.Nullable<System.DateTime> evaluation_date
		{
			get
			{
				return this._evaluation_date;
			}
			set
			{
				if ((this._evaluation_date != value))
				{
					this._evaluation_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriteriaID", DbType="NVarChar(50)")]
		public string CriteriaID
		{
			get
			{
				return this._CriteriaID;
			}
			set
			{
				if ((this._CriteriaID != value))
				{
					this._CriteriaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Criteria_result", DbType="Int")]
		public System.Nullable<int> Criteria_result
		{
			get
			{
				return this._Criteria_result;
			}
			set
			{
				if ((this._Criteria_result != value))
				{
					this._Criteria_result = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acc_year", DbType="Date")]
		public System.Nullable<System.DateTime> Acc_year
		{
			get
			{
				return this._Acc_year;
			}
			set
			{
				if ((this._Acc_year != value))
				{
					this._Acc_year = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Evaluation_Result")]
	public partial class TBL_Evaluation_Result
	{
		
		private int _id;
		
		private string _mentor_ID;
		
		private string _evaluator_id;
		
		private System.Nullable<float> _result;
		
		public TBL_Evaluation_Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mentor_ID", DbType="NVarChar(50)")]
		public string mentor_ID
		{
			get
			{
				return this._mentor_ID;
			}
			set
			{
				if ((this._mentor_ID != value))
				{
					this._mentor_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaluator_id", DbType="NVarChar(50)")]
		public string evaluator_id
		{
			get
			{
				return this._evaluator_id;
			}
			set
			{
				if ((this._evaluator_id != value))
				{
					this._evaluator_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result", DbType="Real")]
		public System.Nullable<float> result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this._result = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_EvaluationCriteria_catagory")]
	public partial class TBL_EvaluationCriteria_catagory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CriteriaID;
		
		private string _CriteriaName;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCriteriaIDChanging(string value);
    partial void OnCriteriaIDChanged();
    partial void OnCriteriaNameChanging(string value);
    partial void OnCriteriaNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_EvaluationCriteria_catagory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriteriaID", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CriteriaID
		{
			get
			{
				return this._CriteriaID;
			}
			set
			{
				if ((this._CriteriaID != value))
				{
					this.OnCriteriaIDChanging(value);
					this.SendPropertyChanging();
					this._CriteriaID = value;
					this.SendPropertyChanged("CriteriaID");
					this.OnCriteriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriteriaName", DbType="NVarChar(200)")]
		public string CriteriaName
		{
			get
			{
				return this._CriteriaName;
			}
			set
			{
				if ((this._CriteriaName != value))
				{
					this.OnCriteriaNameChanging(value);
					this.SendPropertyChanging();
					this._CriteriaName = value;
					this.SendPropertyChanged("CriteriaName");
					this.OnCriteriaNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Mentor")]
	public partial class TBL_Mentor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mentor_id;
		
		private string _first_name;
		
		private string _middle_name;
		
		private string _last_name;
		
		private string _email;
		
		private string _departement;
		
		private string _specialization;
		
		private System.Nullable<System.DateTime> _Reg_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmentor_idChanging(string value);
    partial void Onmentor_idChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onmiddle_nameChanging(string value);
    partial void Onmiddle_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndepartementChanging(string value);
    partial void OndepartementChanged();
    partial void OnspecializationChanging(string value);
    partial void OnspecializationChanged();
    partial void OnReg_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReg_DateChanged();
    #endregion
		
		public TBL_Mentor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mentor_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mentor_id
		{
			get
			{
				return this._mentor_id;
			}
			set
			{
				if ((this._mentor_id != value))
				{
					this.Onmentor_idChanging(value);
					this.SendPropertyChanging();
					this._mentor_id = value;
					this.SendPropertyChanged("mentor_id");
					this.Onmentor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NChar(10)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middle_name", DbType="NVarChar(50)")]
		public string middle_name
		{
			get
			{
				return this._middle_name;
			}
			set
			{
				if ((this._middle_name != value))
				{
					this.Onmiddle_nameChanging(value);
					this.SendPropertyChanging();
					this._middle_name = value;
					this.SendPropertyChanged("middle_name");
					this.Onmiddle_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departement", DbType="NVarChar(50)")]
		public string departement
		{
			get
			{
				return this._departement;
			}
			set
			{
				if ((this._departement != value))
				{
					this.OndepartementChanging(value);
					this.SendPropertyChanging();
					this._departement = value;
					this.SendPropertyChanged("departement");
					this.OndepartementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialization", DbType="NVarChar(50)")]
		public string specialization
		{
			get
			{
				return this._specialization;
			}
			set
			{
				if ((this._specialization != value))
				{
					this.OnspecializationChanging(value);
					this.SendPropertyChanging();
					this._specialization = value;
					this.SendPropertyChanged("specialization");
					this.OnspecializationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reg_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Reg_Date
		{
			get
			{
				return this._Reg_Date;
			}
			set
			{
				if ((this._Reg_Date != value))
				{
					this.OnReg_DateChanging(value);
					this.SendPropertyChanging();
					this._Reg_Date = value;
					this.SendPropertyChanged("Reg_Date");
					this.OnReg_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Mentor_evaluation_Result")]
	public partial class TBL_Mentor_evaluation_Result
	{
		
		private int _id;
		
		private string _mentor_name;
		
		private System.Nullable<float> _Totalresult;
		
		public TBL_Mentor_evaluation_Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mentor_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string mentor_name
		{
			get
			{
				return this._mentor_name;
			}
			set
			{
				if ((this._mentor_name != value))
				{
					this._mentor_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Totalresult", DbType="Real")]
		public System.Nullable<float> Totalresult
		{
			get
			{
				return this._Totalresult;
			}
			set
			{
				if ((this._Totalresult != value))
				{
					this._Totalresult = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Menu")]
	public partial class TBL_Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MenuId;
		
		private string _ParentMenu;
		
		private string _MenuName;
		
		private string _Link;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuIdChanging(string value);
    partial void OnMenuIdChanged();
    partial void OnParentMenuChanging(string value);
    partial void OnParentMenuChanged();
    partial void OnMenuNameChanging(string value);
    partial void OnMenuNameChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public TBL_Menu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MenuId
		{
			get
			{
				return this._MenuId;
			}
			set
			{
				if ((this._MenuId != value))
				{
					this.OnMenuIdChanging(value);
					this.SendPropertyChanging();
					this._MenuId = value;
					this.SendPropertyChanged("MenuId");
					this.OnMenuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentMenu", DbType="NVarChar(50)")]
		public string ParentMenu
		{
			get
			{
				return this._ParentMenu;
			}
			set
			{
				if ((this._ParentMenu != value))
				{
					this.OnParentMenuChanging(value);
					this.SendPropertyChanging();
					this._ParentMenu = value;
					this.SendPropertyChanged("ParentMenu");
					this.OnParentMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuName", DbType="NVarChar(50)")]
		public string MenuName
		{
			get
			{
				return this._MenuName;
			}
			set
			{
				if ((this._MenuName != value))
				{
					this.OnMenuNameChanging(value);
					this.SendPropertyChanging();
					this._MenuName = value;
					this.SendPropertyChanged("MenuName");
					this.OnMenuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(50)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Student")]
	public partial class TBL_Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StudID;
		
		private string _First_Name;
		
		private string _Middle_Name;
		
		private string _Last_Name;
		
		private System.Nullable<int> _Cohort;
		
		private System.Nullable<int> _Age;
		
		private string _Sex;
		
		private string _Nationality;
		
		private string _Dept_code;
		
		private string _Acadmic_year;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private EntityRef<TBL_Student> _TBL_Student2;
		
		private EntityRef<TBL_Student> _TBL_Student1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudIDChanging(string value);
    partial void OnStudIDChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnMiddle_NameChanging(string value);
    partial void OnMiddle_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnCohortChanging(System.Nullable<int> value);
    partial void OnCohortChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnDept_codeChanging(string value);
    partial void OnDept_codeChanged();
    partial void OnAcadmic_yearChanging(string value);
    partial void OnAcadmic_yearChanged();
    partial void OnRegistration_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegistration_DateChanged();
    #endregion
		
		public TBL_Student()
		{
			this._TBL_Student2 = default(EntityRef<TBL_Student>);
			this._TBL_Student1 = default(EntityRef<TBL_Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StudID
		{
			get
			{
				return this._StudID;
			}
			set
			{
				if ((this._StudID != value))
				{
					if (this._TBL_Student1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudIDChanging(value);
					this.SendPropertyChanging();
					this._StudID = value;
					this.SendPropertyChanged("StudID");
					this.OnStudIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="NVarChar(50)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middle_Name", DbType="NVarChar(50)")]
		public string Middle_Name
		{
			get
			{
				return this._Middle_Name;
			}
			set
			{
				if ((this._Middle_Name != value))
				{
					this.OnMiddle_NameChanging(value);
					this.SendPropertyChanging();
					this._Middle_Name = value;
					this.SendPropertyChanged("Middle_Name");
					this.OnMiddle_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(50)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cohort", DbType="Int")]
		public System.Nullable<int> Cohort
		{
			get
			{
				return this._Cohort;
			}
			set
			{
				if ((this._Cohort != value))
				{
					this.OnCohortChanging(value);
					this.SendPropertyChanging();
					this._Cohort = value;
					this.SendPropertyChanged("Cohort");
					this.OnCohortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(50)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="NVarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_code", DbType="NVarChar(50)")]
		public string Dept_code
		{
			get
			{
				return this._Dept_code;
			}
			set
			{
				if ((this._Dept_code != value))
				{
					this.OnDept_codeChanging(value);
					this.SendPropertyChanging();
					this._Dept_code = value;
					this.SendPropertyChanged("Dept_code");
					this.OnDept_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acadmic_year", DbType="NVarChar(50)")]
		public string Acadmic_year
		{
			get
			{
				return this._Acadmic_year;
			}
			set
			{
				if ((this._Acadmic_year != value))
				{
					this.OnAcadmic_yearChanging(value);
					this.SendPropertyChanging();
					this._Acadmic_year = value;
					this.SendPropertyChanged("Acadmic_year");
					this.OnAcadmic_yearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this.OnRegistration_DateChanging(value);
					this.SendPropertyChanging();
					this._Registration_Date = value;
					this.SendPropertyChanged("Registration_Date");
					this.OnRegistration_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_Student_TBL_Student", Storage="_TBL_Student2", ThisKey="StudID", OtherKey="StudID", IsUnique=true, IsForeignKey=false)]
		public TBL_Student TBL_Student2
		{
			get
			{
				return this._TBL_Student2.Entity;
			}
			set
			{
				TBL_Student previousValue = this._TBL_Student2.Entity;
				if (((previousValue != value) 
							|| (this._TBL_Student2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_Student2.Entity = null;
						previousValue.TBL_Student1 = null;
					}
					this._TBL_Student2.Entity = value;
					if ((value != null))
					{
						value.TBL_Student1 = this;
					}
					this.SendPropertyChanged("TBL_Student2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_Student_TBL_Student", Storage="_TBL_Student1", ThisKey="StudID", OtherKey="StudID", IsForeignKey=true)]
		public TBL_Student TBL_Student1
		{
			get
			{
				return this._TBL_Student1.Entity;
			}
			set
			{
				TBL_Student previousValue = this._TBL_Student1.Entity;
				if (((previousValue != value) 
							|| (this._TBL_Student1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_Student1.Entity = null;
						previousValue.TBL_Student2 = null;
					}
					this._TBL_Student1.Entity = value;
					if ((value != null))
					{
						value.TBL_Student2 = this;
						this._StudID = value.StudID;
					}
					else
					{
						this._StudID = default(string);
					}
					this.SendPropertyChanged("TBL_Student1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_UsermenuRole")]
	public partial class TBL_UsermenuRole
	{
		
		private int _id;
		
		private string _Username;
		
		private string _MenuId;
		
		private System.Nullable<int> _Status;
		
		private string _Assignedby;
		
		private System.Nullable<System.DateTime> _date;
		
		public TBL_UsermenuRole()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuId", DbType="NVarChar(50)")]
		public string MenuId
		{
			get
			{
				return this._MenuId;
			}
			set
			{
				if ((this._MenuId != value))
				{
					this._MenuId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assignedby", DbType="NVarChar(50)")]
		public string Assignedby
		{
			get
			{
				return this._Assignedby;
			}
			set
			{
				if ((this._Assignedby != value))
				{
					this._Assignedby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
